/**
 * Reviewed knowledge joins the site and the chat's corpus through publication,
 * and nothing else does (RULE-ASK-PUBLISHED-ONLY). The fixture is a model of
 * its own, the worked example copied into a temporary repository, with three
 * knowledge records: one approved, public and reviewed against its sources as
 * they are; one the same but a draft; one approved but reviewed against a
 * source that has since changed. `intentset publish` releases only the first.
 */
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { after, test } from "node:test";
import { build, canonicalUrl, knowledgePath } from "../build.ts";
import { buildCorpus } from "../corpus.ts";
import { publishedKnowledge } from "../knowledge.ts";

const repoRoot = resolve(import.meta.dirname, "..", "..");
const example = join(repoRoot, "examples", "scheduling");
const fixture = await mkdtemp(join(tmpdir(), "intentset-knowledge-model-"));
const dist = await mkdtemp(join(tmpdir(), "intentset-knowledge-site-"));
after(async () => {
  await rm(fixture, { recursive: true, force: true });
  await rm(dist, { recursive: true, force: true });
});

await cp(example, join(fixture, "product"), { recursive: true });
await mkdir(join(fixture, ".intentset"));
await writeFile(
  join(fixture, ".intentset", "config.yaml"),
  'repository: "fixture/knowledge"\nscope:\n  - "product/**/*.md"\nregistries: "product/registries.yaml"\n',
);
const sha = async (file: string) =>
  createHash("sha256")
    .update(await readFile(join(fixture, "product", file)))
    .digest("hex");
const pins = {
  "BEH-ASMT-SCHEDULE": await sha("BEH-ASMT-SCHEDULE.md"),
  "RULE-ASMT-AUTH": await sha("RULE-ASMT-AUTH.md"),
  "RULE-ASMT-FUTURE": await sha("RULE-ASMT-FUTURE.md"),
};
const kb = await readFile(join(example, "KB-ASMT-SCHEDULE.md"), "utf8");

/** The example's knowledge record, made public, with the given id, status and review pins. */
function knowledge(id: string, status: string, sources: Record<string, string>): string {
  const pinLines = Object.entries(sources)
    .map(([source, hash]) => `        ${source}: ${hash}`)
    .join("\n");
  return kb
    .replace("id: KB-ASMT-SCHEDULE", `id: ${id}`)
    .replace("status: draft", `status: ${status}`)
    .replace("visibility: customer", "visibility: public")
    .replace(
      "  revision: 1\n",
      `  revision: 1\n  reviewedBy: team-assessment\n  reviewedAt: '2026-09-30'\n  extensions:\n    intentset.org/review:\n      sources:\n${pinLines}\n`,
    )
    .replace("# Prepare a scheduled student assessment", `# Prepare a scheduled student assessment (${id})`)
    .replace("title: Prepare a scheduled student assessment", `title: Prepare a scheduled student assessment (${id})`);
}
await writeFile(join(fixture, "product", "KB-ASMT-SCHEDULE.md"), knowledge("KB-ASMT-SCHEDULE", "approved", pins));
await writeFile(join(fixture, "product", "KB-ASMT-DRAFT.md"), knowledge("KB-ASMT-DRAFT", "draft", pins));
await writeFile(
  join(fixture, "product", "KB-ASMT-STALE.md"),
  knowledge("KB-ASMT-STALE", "approved", { ...pins, "RULE-ASMT-FUTURE": "0".repeat(64) }),
);

test("publication releases the approved, reviewed, public record and neither the draft nor the stale one", async () => {
  const released = await publishedKnowledge(fixture);
  assert.deepEqual(
    released.map(({ record }) => record.id),
    ["KB-ASMT-SCHEDULE"],
  );
  const [{ record, body }] = released;
  assert.equal(record.file, "product/KB-ASMT-SCHEDULE.md");
  assert.match(body, /^# Prepare a scheduled student assessment/);
  assert.match(body, /Choose a published assessment/);
  assert.doesNotMatch(body, /^---|intentset-publication|Generated by intentset publish/m);
});

test("the corpus carries the released record as knowledge, at the page the site builds for it", async () => {
  const corpus = await buildCorpus({ modelRoot: fixture });
  const docs = corpus.documents.filter((d) => d.kind === "knowledge");
  assert.deepEqual(
    docs.map((d) => [d.url, d.source]),
    [[canonicalUrl(knowledgePath("KB-ASMT-SCHEDULE")), "product/KB-ASMT-SCHEDULE.md"]],
  );
  assert.match(docs[0].text, /Choose a published assessment/);
  for (const d of corpus.documents) assert.doesNotMatch(d.url, /KB-ASMT-(DRAFT|STALE)/);

  const pages = await build(dist, { askUrl: null, modelRoot: fixture });
  assert.ok(pages.includes(knowledgePath("KB-ASMT-SCHEDULE")));
  assert.ok(pages.includes("knowledge/index.html"));
  assert.equal(
    pages.some((page) => /KB-ASMT-(DRAFT|STALE)/.test(page)),
    false,
  );
  const page = await readFile(join(dist, knowledgePath("KB-ASMT-SCHEDULE")), "utf8");
  assert.match(page, /Choose a published assessment/);
  // The page sits in the Reference rail, which lists the published knowledge's index, and the index lists it.
  assert.match(page, /<nav class="site-rail" aria-label="Reference">[\s\S]*href="\.\.\/\.\.\/knowledge\/index\.html"/);
  const index = await readFile(join(dist, "knowledge", "index.html"), "utf8");
  assert.match(index, /href="KB-ASMT-SCHEDULE\/index\.html"/);
});

test("this repository's model releases exactly what the corpus and the site carry as knowledge", async () => {
  const released = (await publishedKnowledge(repoRoot)).map(({ record }) => canonicalUrl(knowledgePath(record.id)));
  const corpus = await buildCorpus();
  assert.deepEqual(
    corpus.documents.filter((d) => d.kind === "knowledge").map((d) => d.url),
    released,
  );
});
