/**
 * Retrieval chunks (Core §9): each published document split by level-two
 * heading, then by paragraph where a section is longer than `maxChars`. Every
 * chunk carries its document's publication block unchanged, so the access
 * filters and provenance that held for the document hold for each piece of it
 * and a retriever filters on the same fields before anything is assembled.
 *
 * Only published documents are chunked: chunks are made from the output of
 * `publish`, never from canonical files.
 */
import { collectHeadings } from "@intentset/core";
import type { PublicationMeta } from "./generate.ts";

export interface ChunkOptions {
  /** Upper bound on a chunk's text length; a single word longer than it is cut. Default 1200. */
  maxChars?: number;
}

export interface Chunk {
  /** `<document ID>/<n>`, n from 1 in document order. */
  id: string;
  document: string;
  /** The document's level-one heading, or its ID when it has none. */
  title: string;
  /** The level-two heading the chunk falls under, or null before the first one. */
  heading: string | null;
  text: string;
  publication: PublicationMeta;
}

/** What `toChunks` needs of a published document. */
export interface ChunkSource {
  id: string;
  markset: string;
  publication: PublicationMeta;
}

export function toChunks(documents: readonly ChunkSource[], options: ChunkOptions = {}): Chunk[] {
  const maxChars = options.maxChars ?? 1200;
  if (!Number.isInteger(maxChars) || maxChars < 1) throw new RangeError("maxChars must be a positive integer");
  const chunks: Chunk[] = [];
  for (const document of [...documents].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))) {
    const lines = bodyLines(document.markset);
    const headings = collectHeadings(lines, 0);
    const title = headings.find((h) => h.depth === 1)?.text ?? document.id;
    const skip = new Set(headings.filter((h) => h.depth <= 2).map((h) => h.line - 1));
    const sections: { heading: string | null; lines: string[] }[] = [{ heading: null, lines: [] }];
    const starts = new Map(headings.filter((h) => h.depth === 2).map((h) => [h.line - 1, h.text]));
    lines.forEach((line, i) => {
      const heading = starts.get(i);
      if (heading !== undefined) sections.push({ heading, lines: [] });
      else if (!skip.has(i)) sections[sections.length - 1].lines.push(line);
    });
    let n = 0;
    for (const section of sections) {
      for (const text of pack(blocks(section.lines), maxChars)) {
        n++;
        chunks.push({
          id: `${document.id}/${n}`,
          document: document.id,
          title,
          heading: section.heading,
          text,
          publication: document.publication,
        });
      }
    }
  }
  return chunks;
}

/** The body of a generated document: after the frontmatter and the generated-file marker. */
function bodyLines(markset: string): string[] {
  const lines = markset.split("\n");
  let start = 0;
  if (lines[0] === "---") {
    const close = lines.indexOf("---", 1);
    start = close === -1 ? 0 : close + 1;
  }
  if (lines[start]?.startsWith("<!-- Generated by intentset publish")) start++;
  return lines.slice(start);
}

/** Blank-line separated blocks, with a fenced code block kept whole. */
function blocks(lines: readonly string[]): string[] {
  const out: string[] = [];
  let current: string[] = [];
  let fence: string | null = null;
  const flush = () => {
    if (current.some((line) => line.trim() !== "")) out.push(current.join("\n").trim());
    current = [];
  };
  for (const line of lines) {
    const marker = /^ {0,3}(`{3,}|~{3,})/.exec(line)?.[1] ?? null;
    if (fence === null && marker !== null) fence = marker;
    else if (fence !== null && marker !== null && marker[0] === fence[0] && marker.length >= fence.length) fence = null;
    if (fence === null && marker === null && line.trim() === "") flush();
    else current.push(line);
  }
  flush();
  return out;
}

/** Greedy packing of blocks into texts no longer than `max`, splitting a block only when it alone is longer. */
function pack(items: readonly string[], max: number): string[] {
  const out: string[] = [];
  let current = "";
  for (const item of items.flatMap((block) => split(block, max))) {
    if (current === "") current = item;
    else if (current.length + 2 + item.length <= max) current = `${current}\n\n${item}`;
    else {
      out.push(current);
      current = item;
    }
  }
  if (current !== "") out.push(current);
  return out;
}

/** A block cut at whitespace into pieces no longer than `max`; a word longer than `max` is cut where it must be. */
function split(block: string, max: number): string[] {
  const out: string[] = [];
  let rest = block;
  while (rest.length > max) {
    const cut = Math.max(rest.lastIndexOf(" ", max), rest.lastIndexOf("\n", max));
    const at = cut > 0 ? cut : max;
    out.push(rest.slice(0, at).trimEnd());
    rest = rest.slice(at).trimStart();
  }
  if (rest !== "") out.push(rest);
  return out;
}
