/**
 * Generated Markset for one published knowledge artifact (Core §9,
 * spec/publication.md).
 *
 * The document is the knowledge body, unchanged, under frontmatter that
 * carries `markset: 0` and a top-level `intentset-publication` block: the
 * generated profile `intentset/publication/0.1`, marked derived, with the
 * provenance Core §9 requires. It is a top-level key, not `intentset:`, so
 * nothing reads a generated document as a canonical record. A comment line
 * after the frontmatter says the same to a person opening the file.
 *
 * Provenance names only what the projection may show. The knowledge's own
 * path appears only in a projection that admits internal records; sources
 * outside the projection are counted, not named; availability is the
 * request's own values, so a document does not list the other editions,
 * roles or releases its knowledge also serves.
 *
 * The result is checked as Markset before it is emitted: a Markset error is
 * PUB003, and a `:::` directive outside Markset's vocabulary is PUB004
 * (CLAUDE.md invariant 5: profiles never add a directive).
 */
import type { Artifact, Diagnostic, Graph, Visibility } from "@intentset/core";
import { marksetCarrier } from "@intentset/markset-adapter";
import { BLOCK_DIRECTIVE_NAMES, parseDocument } from "@markset-lang/parser";
import { bodyLineOffset } from "./body.ts";
import { publicationDiagnostic, sortedUnique } from "./diagnostic.ts";
import type { Snapshot } from "./project.ts";
import { type PublicationRequest, admits } from "./request.ts";
import { type YamlValue, emitYaml } from "./yaml.ts";

export const PUBLICATION_PROFILE = "intentset/publication/0.1";
/** The top-level frontmatter key of a generated document. */
export const PUBLICATION_KEY = "intentset-publication";

export interface SourceStamp {
  id: string;
  /** The artifact's `revision`, or null when it declares none. */
  revision: number | null;
  sourceHash: string;
}

/** The `intentset-publication` block, in the order it is written. */
export interface PublicationMeta {
  profile: typeof PUBLICATION_PROFILE;
  derived: true;
  /** The projection the document was generated for; the document is as restricted as that projection. */
  projection: Visibility;
  /** The knowledge itself; `path` only in a projection that admits internal records. */
  source: SourceStamp & { path?: string };
  /** Explained artifacts the projection admits, sorted by ID. */
  sources: SourceStamp[];
  /** How many explained artifacts are outside the projection and so not named. */
  withheldSources: number;
  snapshot: Snapshot;
  audience: string;
  /** The request's values, and the flags the knowledge requires (every one of them named by the request). */
  availability: { product: string; release: string; role: string; edition: string; flags: string[] };
  reviewer: string;
  reviewedAt: string;
  publishedAt: string;
}

export interface GenerateOptions {
  snapshot: Snapshot;
  publishedAt: string;
}

export interface GeneratedDocument {
  id: string;
  /** `<ID>.md`. */
  path: string;
  markset: string;
  publication: PublicationMeta;
}

/** The line after the frontmatter that marks a generated file. */
export function markerLine(id: string): string {
  return `<!-- Generated by intentset publish from ${id}; do not edit. -->`;
}

/** The provenance block for a knowledge artifact already selected by the projection and current in review. */
export function publicationMeta(
  graph: Graph,
  artifact: Artifact,
  request: PublicationRequest,
  options: GenerateOptions,
): PublicationMeta {
  const { meta } = artifact;
  if (meta.reviewedBy === undefined || meta.reviewedAt === undefined) {
    throw new Error(`${meta.id} has no review; only knowledge the projection selected is generated`);
  }
  const source: PublicationMeta["source"] = {
    id: meta.id,
    revision: meta.revision ?? null,
    sourceHash: artifact.sourceHash,
  };
  if (admits(request, "internal")) source.path = artifact.path;
  const sources: SourceStamp[] = [];
  let withheldSources = 0;
  for (const id of sortedUnique(meta.links.explains ?? [])) {
    const explained = graph.artifacts.get(id);
    if (explained === undefined || !admits(request, explained.meta.visibility)) withheldSources++;
    else sources.push({ id, revision: explained.meta.revision ?? null, sourceHash: explained.sourceHash });
  }
  return {
    profile: PUBLICATION_PROFILE,
    derived: true,
    projection: request.visibility,
    source,
    sources,
    withheldSources,
    snapshot: { commit: options.snapshot.commit, graphHash: options.snapshot.graphHash },
    audience: request.audience,
    availability: {
      product: request.product,
      release: request.release,
      role: request.role,
      edition: request.edition,
      flags: sortedUnique((meta.availability?.flags ?? []).filter((flag) => request.flags.includes(flag))),
    },
    reviewer: meta.reviewedBy,
    reviewedAt: meta.reviewedAt,
    publishedAt: options.publishedAt,
  };
}

/** The document text, and the 1-based line the body's first line lands on. */
export function marksetSource(publication: PublicationMeta, body: string): { source: string; bodyStartLine: number } {
  const yaml = emitYaml({ markset: 0, [PUBLICATION_KEY]: publication as unknown as YamlValue });
  const head = `---\n${yaml}---\n${markerLine(publication.source.id)}\n`;
  const separated = body.startsWith("\n");
  const headLines = head.split("\n").length - 1;
  return {
    source: separated ? head + body : `${head}\n${body}`,
    bodyStartLine: headLines + (separated ? 1 : 2),
  };
}

/** Generate and check one document. A document with any error is not returned. */
export function generateDocument(
  graph: Graph,
  artifact: Artifact,
  request: PublicationRequest,
  options: GenerateOptions,
): { document: GeneratedDocument | null; diagnostics: Diagnostic[] } {
  const id = artifact.meta.id;
  const path = `${id}.md`;
  let publication: PublicationMeta;
  let generated: { source: string; bodyStartLine: number };
  try {
    publication = publicationMeta(graph, artifact, request, options);
    generated = marksetSource(publication, artifact.body);
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    return {
      document: null,
      diagnostics: [
        publicationDiagnostic({
          code: "PUB003",
          artifact: id,
          path: artifact.path,
          message: `The generated document for ${id} could not be written as Markset: ${reason}.`,
          remediation: "Correct the metadata value named in the message; provenance is written in plain YAML scalars.",
        }),
      ],
    };
  }
  const diagnostics = checkGenerated(artifact, generated.source, generated.bodyStartLine);
  if (diagnostics.length > 0) return { document: null, diagnostics };
  return { document: { id, path, markset: generated.source, publication }, diagnostics };
}

/** PUB004 for a directive outside Markset's vocabulary, PUB003 for every other Markset error. */
export function checkGenerated(artifact: Artifact, source: string, bodyStartLine: number): Diagnostic[] {
  const id = artifact.meta.id;
  const offset = bodyLineOffset(artifact);
  const locate = (line: number | undefined) =>
    line === undefined || offset === null || line < bodyStartLine
      ? undefined
      : { line: line - bodyStartLine + 1 + offset };
  const lines = source.split("\n");
  const parsed = parseDocument(source);
  const diagnostics: Diagnostic[] = [];

  const directiveLines = new Set<number>();
  const visit = (node: unknown): void => {
    if (typeof node !== "object" || node === null) return;
    const n = node as {
      type?: string;
      name?: string | null;
      position?: { start: { line: number } };
      children?: unknown[];
    };
    if (n.type === "directive") {
      const line = n.position?.start.line;
      const name =
        n.name ??
        (line === undefined ? null : (/^\s*:{3,}\s*([A-Za-z][A-Za-z0-9_-]*)/.exec(lines[line - 1])?.[1] ?? null));
      if (name !== null && !BLOCK_DIRECTIVE_NAMES.has(name)) {
        if (line !== undefined) directiveLines.add(line);
        diagnostics.push(
          publicationDiagnostic({
            code: "PUB004",
            artifact: id,
            path: artifact.path,
            location: locate(line),
            message: `${id} uses the directive :::${name}, which is not in Markset's vocabulary.`,
            remediation: `Use one of Markset's constructs (${[...BLOCK_DIRECTIVE_NAMES].join(", ")}) or plain Markdown; an Intentset profile never adds a directive (Core §9).`,
          }),
        );
      }
    }
    for (const child of n.children ?? []) visit(child);
  };
  visit(parsed.ast);

  if (parsed.frontmatter?.markset !== 0) {
    diagnostics.push(
      publicationDiagnostic({
        code: "PUB003",
        artifact: id,
        path: artifact.path,
        message: `The generated frontmatter for ${id} does not read as Markset version 0.`,
        remediation:
          "Report this as a publisher defect; the generated frontmatter must be readable by Markset's own reader.",
      }),
    );
  }
  for (const d of marksetCarrier(`${id}.md`, source).syntax) {
    if (d.severity !== "error" || (d.location !== undefined && directiveLines.has(d.location.line))) continue;
    diagnostics.push(
      publicationDiagnostic({
        code: "PUB003",
        artifact: id,
        path: artifact.path,
        location: locate(d.location?.line),
        message: `The generated document for ${id} is not valid Markset: ${d.code}, ${d.message.replace(/\.$/, "")}.`,
        remediation:
          "Fix the Markset syntax in the knowledge body; the document is not emitted until it parses without errors.",
      }),
    );
  }
  return diagnostics;
}
