/**
 * Retrieval chunks (Core §9): split by level-two heading, then by paragraph,
 * each chunk inheriting its document's access filters and provenance.
 */
import assert from "node:assert/strict";
import { test } from "node:test";
import { type PublicationMeta, marksetSource, publish, toChunks } from "../src/index.ts";
import { PUBLISHED_AT, customer, example, reviewed, snapshotOf } from "./harness.ts";

const LONG = "Choose a published assessment and a class you can manage, then pick a future release time.";

function published(body: string) {
  const { graph, registries } = example({ kb: reviewed(), body });
  const result = publish(graph, registries, customer(), { snapshot: snapshotOf(graph), publishedAt: PUBLISHED_AT });
  assert.deepEqual(result.diagnostics, []);
  return result.documents;
}

const BODY = [
  "",
  "# Prepare a scheduled assessment",
  "",
  "A short introduction.",
  "",
  "## Guidance",
  "",
  LONG,
  "",
  LONG,
  "",
  "```text",
  "first line",
  "",
  "after a blank line inside the fence",
  "```",
  "",
  "## Troubleshooting",
  "",
  "If scheduling is rejected, check your class permissions.",
  "",
].join("\n");

test("chunks follow level-two sections, keep the heading, and drop the title and marker from the text", () => {
  const chunks = toChunks(published(BODY));
  assert.deepEqual(
    chunks.map((c) => [c.id, c.heading]),
    [
      ["KB-ASMT-SCHEDULE/1", null],
      ["KB-ASMT-SCHEDULE/2", "Guidance"],
      ["KB-ASMT-SCHEDULE/3", "Troubleshooting"],
    ],
  );
  assert.equal(chunks[0].text, "A short introduction.");
  assert.equal(chunks[0].title, "Prepare a scheduled assessment");
  assert.ok(chunks.every((c) => !c.text.includes("Generated by") && !c.text.includes("# ")));
  assert.match(chunks[1].text, /```text\nfirst line\n\nafter a blank line inside the fence\n```$/);
});

test("a long section splits at paragraphs, a fenced block stays whole, and no chunk passes the bound", () => {
  const chunks = toChunks(published(BODY), { maxChars: 120 });
  const guidance = chunks.filter((c) => c.heading === "Guidance");
  assert.deepEqual(
    guidance.map((c) => c.text),
    [LONG, LONG, "```text\nfirst line\n\nafter a blank line inside the fence\n```"],
  );
  assert.ok(chunks.every((c) => c.text.length <= 120));
});

test("a paragraph longer than the bound is cut at whitespace, and a word longer than it where it must be", () => {
  const chunks = toChunks(published(BODY), { maxChars: 40 });
  assert.ok(
    chunks.every((c) => c.text.length <= 40),
    JSON.stringify(chunks.map((c) => c.text)),
  );
  assert.ok(chunks.some((c) => c.text.startsWith("Choose a published assessment")));
  const words = toChunks(
    [{ id: "KB-W", markset: `---\nmarkset: 0\n---\n\n# W\n\n${"x".repeat(25)}\n`, publication: {} as PublicationMeta }],
    { maxChars: 10 },
  );
  assert.deepEqual(
    words.map((c) => c.text),
    ["xxxxxxxxxx", "xxxxxxxxxx", "xxxxx"],
  );
});

test("every chunk carries its document's publication block: the same access filters and provenance", () => {
  const documents = published(BODY);
  for (const chunk of toChunks(documents, { maxChars: 80 })) {
    assert.equal(chunk.document, "KB-ASMT-SCHEDULE");
    assert.deepEqual(chunk.publication, documents[0].publication);
    assert.equal(chunk.publication.projection, "customer");
    assert.equal(chunk.publication.audience, "teacher");
    assert.equal(chunk.publication.availability.release, "pilot-1");
  }
});

test("documents are chunked in ID order, and a bad bound is refused", () => {
  const meta = (id: string) => ({ source: { id } }) as PublicationMeta;
  const doc = (id: string) => ({
    id,
    markset: marksetSource(meta(id), "\n# T\n\nText.\n").source,
    publication: meta(id),
  });
  assert.deepEqual(
    toChunks([doc("KB-B"), doc("KB-A")]).map((c) => c.id),
    ["KB-A/1", "KB-B/1"],
  );
  assert.throws(() => toChunks([], { maxChars: 0 }), RangeError);
  assert.throws(() => toChunks([], { maxChars: 1.5 }), RangeError);
});
